WARNING | 2021-12-02 00:46:04,238 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: mu_mh_context
WARNING | 2021-12-02 00:46:04,238 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: mu_maildir_record
WARNING | 2021-12-02 00:46:04,238 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: mu_imaps_record
WARNING | 2021-12-02 00:46:04,238 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: mu_c_tab
WARNING | 2021-12-02 00:46:04,239 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: mu_smtps_record
WARNING | 2021-12-02 00:46:04,239 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: mu_nntp_record
WARNING | 2021-12-02 00:46:04,239 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: mu_smtp_record
WARNING | 2021-12-02 00:46:04,239 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: mu_pops_record
WARNING | 2021-12-02 00:46:04,239 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: mu_mh_record
WARNING | 2021-12-02 00:46:04,239 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: mu_prog_record
WARNING | 2021-12-02 00:46:04,239 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: mu_strin
WARNING | 2021-12-02 00:46:04,239 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: mu_pop_record
WARNING | 2021-12-02 00:46:04,239 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: mu_mh_profile
WARNING | 2021-12-02 00:46:04,239 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: mu_program_name
WARNING | 2021-12-02 00:46:04,239 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: mu_sendmail_record
WARNING | 2021-12-02 00:46:04,240 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: mu_mbox_record
WARNING | 2021-12-02 00:46:04,240 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: mu_imap_record
WARNING | 2021-12-02 00:46:04,240 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: mu_strerr
WARNING | 2021-12-02 00:46:04,240 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: mu_strout
WARNING | 2021-12-02 00:46:04,240 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: mu_version_copyright
WARNING | 2021-12-02 00:46:04,247 | cle.loader | For more information about "Symbol was allocated without a known size", see https://docs.angr.io/extending-angr/environment#simdata
Fatal Python error: Cannot recover from stack overflow.

Current thread 0x00007faf9cfc70c0 (most recent call first):
  File "/home/ittay.al/miniconda3/envs/tf1/lib/python3.7/logging/__init__.py", line 869 in format
  File "/home/ittay.al/miniconda3/envs/tf1/lib/python3.7/logging/__init__.py", line 1025 in emit
  File "/home/ittay.al/miniconda3/envs/tf1/lib/python3.7/logging/__init__.py", line 894 in handle
  File "/home/ittay.al/miniconda3/envs/tf1/lib/python3.7/logging/__init__.py", line 1586 in callHandlers
  File "/home/ittay.al/miniconda3/envs/tf1/lib/python3.7/logging/__init__.py", line 1524 in handle
  File "/home/ittay.al/miniconda3/envs/tf1/lib/python3.7/logging/__init__.py", line 1514 in _log
  File "/home/ittay.al/miniconda3/envs/tf1/lib/python3.7/logging/__init__.py", line 1407 in error
  File "/home/ittay.al/miniconda3/envs/tf1/lib/python3.7/logging/__init__.py", line 1959 in error
  File "paths_constraints_main.py", line 216 in analyze_binary
  File "paths_constraints_main.py", line 188 in generate_dataset
  File "paths_constraints_main.py", line 348 in main
  File "paths_constraints_main.py", line 352 in <module>
timeout: the monitored command dumped core
Aborted
