ERROR   | 2021-12-02 00:52:11,768 | root     | list index out of range
ERROR   | 2021-12-02 00:52:11,768 | root     | got an error while analyzing cmd_quit
Fatal Python error: Cannot recover from MemoryErrors while normalizing exceptions.

Current thread 0x00007f822f12c0c0 (most recent call first):
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/light/light.py", line 446 in handle_vex_block
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/heavy/inspect.py", line 45 in handle_vex_block
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/heavy/actions.py", line 30 in handle_vex_block
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/light/slicing.py", line 26 in handle_vex_block
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/heavy/super_fastpath.py", line 19 in handle_vex_block
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/heavy/heavy.py", line 138 in process_successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/soot/engine.py", line 64 in process_successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/unicorn.py", line 169 in process_successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/hook.py", line 54 in process_successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/syscall.py", line 18 in process_successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/failure.py", line 21 in process_successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/engine.py", line 149 in process
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/light/slicing.py", line 19 in process
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/factory.py", line 60 in successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/sim_manager.py", line 441 in successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/misc/hookset.py", line 80 in __call__
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/exploration_techniques/loop_seer.py", line 98 in successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/misc/hookset.py", line 75 in __call__
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/sim_manager.py", line 402 in step_state
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/sim_manager.py", line 365 in step
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/sim_manager.py", line 280 in run
  File "paths_constraints_main.py", line 48 in analyze_func
  File "paths_constraints_main.py", line 212 in analyze_binary
  File "paths_constraints_main.py", line 188 in generate_dataset
  File "paths_constraints_main.py", line 348 in main
  File "paths_constraints_main.py", line 352 in <module>
Exception ignored in: <generator object WeakSet.__iter__ at 0x7f821e0982d0>
MemoryErrortimeout: the monitored command dumped core
Aborted
